version: '3'

services:
  backend:
    container_name: backend

    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - .:/practice/
      - /practice/node_modules
    ports:
      - 3000:3000

  database:
    container_name: database

    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codecamp
    ports:
      - 3306:3306

  redis:
    container_name: redis

    image: redis:latest
    ports:
      - 6379:6379