version: '3'

services:
  # backend server configure
  backend:
    container_name: backend

    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - .:/practice/
      - /practice/node_modules/
    
    ports:
      - 3000:3000

  # mysql server configure
  database:
    container_name: mysql

    image: mysql:8.0.31
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codecamp
    
    ports:
      - 3306:3306

  # redis server configure
  redis:
    container_name: redis

    image: redis:latest

    ports:
      - 6379:6379

  # elasticksearch server configure
  elasticsearch:
    container_name: elasticsearch

    image: elasticsearch:7.17.0

    environment:
      discovery.type: single-node
    
    ports:
      - 9200:9200

  logstash:
    container_name: logstash

    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar

    image: logstash:7.17.0
