version: '3'

services:
  backend:
    container_name: backend_payment

    build:
      dockerfile: Dockerfile
      context: .

    volumes:
      - .:/practice/
      - /practice/node_modules
    ports:
      - 3000:3000

  database:
    container_name: database_payment

    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codecamp_database
    ports:
      - 3306:3306
