version: '3.7'

services:
  # gateway configure
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    volumes:
      - ./api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - auth
      - stock

  # auth configure
  auth:
    container_name: auth
    build:
      context: ./services/auth/
      dockerfile: Dockerfile
    volumes:
      - ./services/auth/src:/auth/src
  
  # stock configure
  stock:
    container_name: stock
    build:
      context: ./services/stock
      dockerfile: Dockerfile
