version: '3.7'

services:
  backend:
    image: asia.gcr.io/onyx-ivy-377204/backend:0.10
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/practice/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod

  # mysql:
  #   container_name: mysql
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'codecamp'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
